[package]
name = "tidy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
md5 = "0.7.0"
rayon = "1.5.1"
structopt = "0.3.22"
walkdir = "2.3.2"
